### ISSUE TITLE
Raster WorldCopy

### ISSUE THREAD

**Issue by drewjgray** [GeoTIFF/georaster-layer-for-leaflet#35]
Amazing library @DanielJDufour! Is there a way to copy the raster data over to all "copies" of the map? For example, if the user pans the map past -180 or 180 longitude (see screenshot). Thank you! 

<img width="919" alt="Screen Shot 2020-06-21 at 6 55 57 PM" src="https://user-images.githubusercontent.com/6283065/85241582-22c44600-b3f1-11ea-842e-07575c17841d.png">

**Comment by DanielJDufour** [comment]
Hi, @drewjgray .  Thank you for the kind words.  Currently, there doesn't exist this capability, but this is something that could be written.  Would you be interested in submitting a pull request?  Otherwise, I'm happy to work on it, but it may take some time.  Thanks again for brining this to our attention.  It's an issue other users probably have as well!

**Comment by drewjgray** [comment]
I wish I could! Unfortunately I have very little development experience with the inner workings of Leaflet. If you do get time, I think it would be a really useful feature. If there is something you could point me to on learning more about how I could implement this myself I would love to start learning about it. Thank you!

**Comment by DanielJDufour** [comment]
I just fixed this bug and published a new version of georaster-layer-for-leaflet (0.5.0) with this fix.  Let me know if it works! Thanks.

**Comment by drewjgray** [comment]
Amazing, works perfectly @DanielJDufour . Thank you!
