### ISSUE TITLE
Strange gridlines for specific pixelValuesToColorFn

### ISSUE THREAD

**Issue by saveas** [GeoTIFF/georaster-layer-for-leaflet#36]
Hi Daniel and thanks for this amazing plugin!
I run into a strange problem. 
I render a geotiff, and when picking this pixelValuesToColorFn:
```
              pixelValuesToColorFn: values => values[0] === -32768 ? null :
                            (values[0] > -70                    ) ? '#607c3c' :
                            (values[0] > -90  && values[0] <= -70) ? '#809c13' :
                            (values[0] > -100 && values[0] <= -90) ? '#abc32f' :
                            (values[0] > -115 && values[0] <= -100) ? '#b5e550' :
                            (                    values[0] <= -115) ? '#ececa3' :
                            null
```
everything works perfect:
![image](https://user-images.githubusercontent.com/4006954/85872652-b4102f80-b7d8-11ea-96c0-8e80ec7766c4.png)

But with this function that messes with the alpha value:
```
              pixelValuesToColorFn: values => values[0] === -32768 ? null :
                          (values[0] > -140  && values[0] <= -65) ?  `rgba(255, 0, 0, ${((values[0]+60)/80+1).toFixed(2)})` :
                          (values[0] < -140  ) ?  `rgba(255, 0, 0, 0)` :
                          (values[0] > -65  ) ?  `rgba(255, 0, 0, 1)` :
                          null
```
some red grid lines appear in zoom levels >=12
![image](https://user-images.githubusercontent.com/4006954/85873037-41538400-b7d9-11ea-8cdc-77b2a875898f.png)

when I zoom out, the lines disappear
![image](https://user-images.githubusercontent.com/4006954/85873108-5a5c3500-b7d9-11ea-9c91-19b7691529ea.png)

The problem appears both on latest Chrome and Firefox, Leaflet 1.6

here is the tiff file I'm using
[sample.zip](https://github.com/GeoTIFF/georaster-layer-for-leaflet/files/4837803/sample.zip)

Any idea on why this is happening??
Thanks in advance!

**Comment by DanielJDufour** [comment]
I'm also seeing grid lines when I zoom in on the first example.  I'm wondering if it's an issue with Leaflet, but I'm not sure:
<img width="703" alt="Screen Shot 2020-06-27 at 8 04 53 PM" src="https://user-images.githubusercontent.com/4313463/85934526-78956400-b8b1-11ea-8a5b-f23b634a95c7.png">
I'll continue to research and let you know.

**Comment by DanielJDufour** [comment]
I agree that the issue is more pronounced with the second function
<img width="705" alt="Screen Shot 2020-06-28 at 5 53 06 AM" src="https://user-images.githubusercontent.com/4313463/85944288-a60afd80-b903-11ea-8fc6-5617c454b73d.png">

**Comment by DanielJDufour** [comment]
I believe I discovered the issue.  The most immediate solution is to swap out the pixelValuesToColorFn for a customDrawFunction like
```javascript
              customDrawFunction: function({ values, context, x, y, width, height }) {
                const value = values[0];
                let color = null;
                if (value > -140  && value <= -65) color = `rgba(255, 0, 0, ${((value+60)/80+1).toFixed(2)})`;
                else if (value < -140) color = `rgba(255, 0, 0, 0)`;
                else if (value > -65  ) color = `rgba(255, 0, 0, 1)`;
                context.fillStyle = color;
                context.clearRect(x, y, width, height);
                context.fillRect(x, y, width, height);                         
              }   
```
You'll notice the usage of clearRect.  Using clearRect will drag performance, but will help erase the red lines.  The issue is that by changing the alpha value / opacity of colors, there are faint overlaps between rectangles drawn on the canvas.  For example, if one rectangle draws from 0 to 1 and another draws from 1 to 2, they slightly overlap at 1.

Here's an image with a customDrawFunction
<img width="1438" alt="Screen Shot 2020-06-28 at 6 49 56 AM" src="https://user-images.githubusercontent.com/4313463/85945415-97284900-b90b-11ea-80a7-dffa278afcf0.png">
 

Another solution would be to return different colors (rgb, not rgba) and set the layer opacity:
```
            var layer = new GeoRasterLayer({
              georaster,
              opacity: 0.7,
              resolution: 1024,
              pixelValuesToColorFn: values => values[0] === -32768 ? null :
                (values[0] > -140  && values[0] <= -65) ?  `rgb(${(1- ((values[0]+60)/80+1)) * 255}, 0, 0)` :
                (values[0] > -65  ) ?  `rgb(255, 0, 0)` :
                null                                     
            });
```
That results in an image like:
<img width="1440" alt="Screen Shot 2020-06-28 at 6 58 05 AM" src="https://user-images.githubusercontent.com/4313463/85945566-bb385a00-b90c-11ea-9d47-1cd77af407db.png">


There may be better long-term solutions out there.  If anyone else has a solution, I'd be open to a Pull Request.  I've tried a few other approaches for this library before (setting values in an ImageData), but all were less performant.

I'm sorry this isn't a great answer.  Hopefully, we can find something that works.

**Comment by saveas** [comment]
Thanks for the time you spent on this Daniel!
Actually the CustomDrawFunction solution works great, there is a very small performance drag but it is on acceptable level for my project!
Plus I learned more about CustomDrawFunction :)
Thanks again!

**Comment by DanielJDufour** [comment]
Sounds great. Glad to hear it works for you!
